version: 1.0.{build}
clone_depth: 0
image: tadekbiela/heisttown:heisttown_win

configuration:
  - BuildApp

for:
  - matrix:
      only:
        - configuration: BuildApp
    build_script:
      - docker exec heisttown powershell cmake .. && make -j app
