# Get the Qt6 Google Test Windows 10 image from Docker Hub
FROM tadekbiela/cpp_development:cpp_development_windows

# Clone heisttown repository
RUN powershell -Command "git clone https://github.com/TadekBiela/heisttown.git C:\heisttown"

# Set to working directory and build heisttown
WORKDIR "C:\heisttown\build"
RUN powershell -Command "cmake .."
RUN cmake --build . --target all
RUN powershell -Command "git config --global --add safe.directory C:/heisttown"

LABEL Name=heisttown_win
