name: CI
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: tadekbiela/heisttown:heisttown
      env:
        DISPLAY: :0
    env:
      CI: true
    defaults:
      run:
        shell: bash
        working-directory: /usr/src/heisttown/build
    steps:
      - name: build app
        run: |
          git pull
          cmake ../
          make -j app

      - name:  build ut
        run: |
          git pull
          cmake ../
          make -j buildut

      - name: run ut
        run: |
          Xvfb :0 -screen 0 800x600x24 &
          git pull
          cmake ../
          make -j runut

  windows:
    runs-on: windows-2019
    steps:
    - name: Initialize containers
      run: |
        cmd "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchWindowsEngine
        docker pull tadekbiela/heisttown:heisttown_win
        docker create --name ht -i tadekbiela/heisttown:heisttown_win
        docker start ht
      
    - name: build app
      run: docker exec ht powershell "git pull; cmake ..; make -j app"

    - name: build ut
      run: docker exec ht powershell "git pull; cmake ..; make -j buildut"

    - name: run ut
      run: docker exec ht powershell "git pull; cmake ..; make -j runut"
      
    - name: Stop containers
      run: |
        docker stop ht
        docker rm ht
