name: CI
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: tadekbiela/heisttown:heisttown
      env:
        DISPLAY: :0
    env:
      CI: true
    defaults:
      run:
        shell: bash
        working-directory: /usr/src/heisttown/build
    steps:
      - name: build app
        run: |
          git pull
          cmake ../
          make -j app

      - name:  build ut
        run: |
          git pull
          cmake ../
          make -j buildut

      - name: run ut
        run: |
          Xvfb :0 -screen 0 800x600x24 &
          git pull
          cmake ../
          make -j runut

  windows:
    runs-on: windows-latest
    steps:
    - name: build app
      run: docker run --name ht --rm tadekbiela/heisttown:heisttown_win powershell "git pull; cmake ..; make -j app"

    - name: build ut
      run: docker run --name ht --rm tadekbiela/heisttown:heisttown_win powershell "git pull; cmake ..; make -j buildut"

    - name: run ut
      run: docker run --name ht --rm tadekbiela/heisttown:heisttown_win powershell "git pull; cmake ..; make -j runut"
