name: CI
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: tadekbiela/heisttown:heisttown
      env:
        DISPLAY: :0
    env:
      CI: true
    defaults:
      run:
        shell: bash
        working-directory: /usr/src/heisttown/build
    steps:
      - name: build all
        run: |
          Xvfb :0 -screen 0 800x600x24 &
          git pull
          cmake ..
          cmake --build . --target all

      - name: run release
        run: |
          cmake --build . --target Release

      - name: run ut
        run: |
          cmake --build . --target RunAllTests

      - name: run sanitizers
        run: |
          cmake --build . --target Sanitizers

      - name: run valgrind
        run: |
          cmake --build . --target Valgrind

  windows:
    runs-on: windows-2019
    steps:
    - name: Initialize containers
      run: |
        cmd "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchWindowsEngine
        docker pull tadekbiela/heisttown:heisttown_win
        docker create --name ht -i tadekbiela/heisttown:heisttown_win
        docker start ht
      
    - name: build all
      run: docker exec ht powershell "git pull; cmake ..; cmake --build . --target all"

    - name: build release
      run: docker exec ht powershell "git pull; cmake ..; cmake --build . --target Release"

    - name: run ut
      run: docker exec ht powershell "git pull; cmake ..; cmake --build . --target all; cmake --build . --target test"

    - name: run sanitizers
      run: docker exec ht powershell "git pull; cmake -D SANITIZE=ON ..; cmake --build . --target all; cmake --build . --target test"
      
    - name: Stop containers
      run: |
        docker stop ht
        docker rm ht
