name: CI
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: tadekbiela/heisttown:heisttown
      env:
        DISPLAY: :0
    env:
      CI: true
      working-directory: /usr/src/heisttown/build
    steps:
      - name: build app
        run: |
          git pull
          cmake ../
          make -j app

      - name:  build ut
        run: |
          git pull
          cmake ../
          make -j buildut

      - name: run ut
        run: |
          Xvfb :0 -screen 0 800x600x24 &
          git pull
          cmake ../
          make -j runut

  windows:
    runs-on: windows-latest
    container:
      image: tadekbiela/heisttown:heisttown_win
    env:
      CI: true
      working-directory: C:\heisttown\build
    steps:
      - name: build app
        run: |
          git pull
          cmake ../
          make -j app

      - name:  build ut
        run: |
          git pull
          cmake ../
          make -j buildut

      - name: run ut
        run: |
          git pull
          cmake ../
          make -j runut
