name: CI for Windows

on: push

jobs:
  ci_win:
    runs-on: windows-latest

    steps:

    - name: Build App
      run: docker run --name ht --rm tadekbiela/heisttown:heisttown_win powershell "git pull; cmake ..; make -j app"

    - name: Build Uts
      run: docker run --name ht --rm tadekbiela/heisttown:heisttown_win powershell "git pull; cmake ..; make -j buildut"

    - name: Run Uts
      run: docker run --name ht --rm tadekbiela/heisttown:heisttown_win powershell "git pull; cmake ..; make -j runut"
